// This file is used to seed the initial pets database.  

exports.pets = [
  {
    petType: "CAT",
    petColor: "BLACK",
    petSize:"SMALL",
    petGender: "FEMALE",
    petAge: 1,
    petEnvironment: "LOFT",
    petClassifications: {house_trained: true},
    petTemperament: "TIMID",
    petImage: "https://cdn.pixabay.com/photo/2015/08/25/21/58/cat-907749_1280.jpg",
    isAvailable: true,
  },
  {
    petType: "CAT",
    petColor: "ORANGE",
    petSize:"MEDIUM",
    petGender: "MALE",
    petAge: 5,
    petEnvironment: "OTHER",
    petClassifications: {shots_current: true},
    petTemperament: "ENERGETIC",
    petImage: "https://cdn.pixabay.com/photo/2020/03/31/16/18/cat-4988407_1280.jpg",
    isAvailable: true,
  },
  {
    petType: "DOG",
    petColor: "BLACK",
    petSize:"MEDIUM",
    petGender: "MALE",
    petAge: 4,
    petEnvironment: "OTHER",
    petClassifications: {house_trained: true, shots_current: true},
    petTemperament: "AFFECTIONATE",
    petImage: "https://images.pexels.com/photos/10443834/pexels-photo-10443834.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: false,
  },
  {
    petType: "DOG",
    petColor: "MIXED",
    petSize:"SMALL",
    petGender: "WHATEVER",
    petAge: 2,
    petEnvironment: "FARM",
    petClassifications: {house_trained: true, shots_current: true, special_needs: true},
    petTemperament: "INDEPENDENT",
    petImage: "https://images.pexels.com/photos/3763313/pexels-photo-3763313.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "HORSE",
    petColor: "BROWN",
    petSize:"FARM",
    petGender: "FEMALE",
    petAge: 6,
    petEnvironment: "FARM",
    petClassifications: {special_needs: true},
    petTemperament: "TIMID",
    petImage: "https://cdn.pixabay.com/photo/2018/08/13/22/29/horse-3604162_1280.jpg",
    isAvailable: true,
  },
  {
    petType: "HORSE",
    petColor: "WHITE",
    petSize:"LARGE",
    petGender: "MALE",
    petAge: 10,
    petEnvironment: "OTHER",
    petClassifications: {shots_current: true},
    petTemperament: "ENERGETIC",
    petImage: "https://cdn.pixabay.com/photo/2017/06/30/00/04/pony-2456757_1280.jpg",
    isAvailable: false,
  },
  {
    petType: "LIZARD",
    petColor: "BROWN",
    petSize:"SMALL",
    petGender: "MALE",
    petAge: 1,
    petEnvironment: "OTHER",
    petTemperament: "TIMID",
    petImage: "https://images.pexels.com/photos/8162455/pexels-photo-8162455.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: false,
  },
  {
    petType: "LIZARD",
    petColor: "MIXED",
    petSize:"SMALL",
    petGender: "WHATEVER",
    petAge: 2,
    petEnvironment: "APARTMENT",
    petClassifications: {special_needs: true},
    petTemperament: "INDEPENDENT",
    petImage: "https://images.pexels.com/photos/9384357/pexels-photo-9384357.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "FERRET",
    petColor: "WHITE",
    petSize:"SMALL",
    petGender: "FEMALE",
    petAge: 1,
    petEnvironment: "LOFT",
    petClassifications: {house_trained: true, declawed: true},
    petTemperament: "TIMID",
    petImage: "https://images.pexels.com/photos/5403275/pexels-photo-5403275.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAvailable: true,
  },
  {
    petType: "FERRET",
    petColor: "BLACK",
    petSize:"MEDIUM",
    petGender: "WHATEVER",
    petAge: 3,
    petEnvironment: "OTHER",
    petClassifications: {shots_current: true},
    petTemperament: "AFFECTIONATE",
    petImage: "https://images.pexels.com/photos/11928076/pexels-photo-11928076.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "GOLDFISH",
    petColor: "ORANGE",
    petSize:"SMALL",
    petGender: "MALE",
    petAge: 1,
    petEnvironment: "OTHER",
    petClassifications: {special_needs: true},
    petTemperament: "TIMID",
    petImage: "https://images.pexels.com/photos/2053815/pexels-photo-2053815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "GOLDFISH",
    petColor: "MIXED",
    petSize:"SMALL",
    petGender: "WHATEVER",
    petAge: 3,
    petEnvironment: "BOAT",
    petClassifications: {special_needs: true},
    petTemperament: "ENERGETIC",
    petImage: "https://images.pexels.com/photos/8434726/pexels-photo-8434726.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "ROCK",
    petColor: "BROWN",
    petSize:"SMALL",
    petGender: "WHATEVER",
    petAge: 900000,
    petEnvironment: "OTHER",
    petClassifications: {declawed: true},
    petTemperament: "ENERGETIC",
    petImage: "https://images.pexels.com/photos/161702/harmony-relax-rock-moqui-161702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    isAvailable: true,
  },
  {
    petType: "ROCK",
    petColor: "BROWN",
    petSize:"SMALL",
    petGender: "FEMALE",
    petAge: 9999999,
    petEnvironment: "FARM",
    petTemperament: "TIMID",
    petImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4rpOIsjuAYK1eid3CasDdBGPXnXOniKnfIQ&usqp=CAU",
    isAvailable: true,
  },
];
